packages:
  - 'web'
  - 'server'
allowBuilds:
  '"': true
  ',': true
  /: true
  '@': true
  '[': true
  ']': true
  a: true
  b: true
  c: true
  e: true
  g: true
  i: true
  l: true
  m: true
  n: true
  p: true
  r: true
  s: true
  t: true
  y: true
